version: 3
rules:
  zeek:
    detect:
      artifact type: pcap
      event: ingest
      op: exists
      path: /
      target: artifact_event
    namespace: general
    respond:
    - action: service request
      name: zeek
      request:
        action: run_on
        artifact_id: <<routing/log_id>>
        retention: 90