version: 3
rules:
  test-detection:
    detect:
      event: NEW_PROCESS
      path: event/COMMAND_LINE
      op: contains
      value: lc_tracer2
    respond:
      - action: report
        name: tracer-detection
