version: 3
hives:
  dr-general:
    test-detection:
      data:
        detect:
          event: NEW_PROCESS
          op: contains
          path: event/COMMAND_LINE
          value: lc_tracer2
        respond:
        - action: report
          name: tracer-detection
      usr_mtd:
        enabled: true
        expiry: 0
        tags: []